#!/usr/bin/env ruby

require 'QuizletNerdClient'
require 'rubygems'
require 'commander'
require 'yaml'
require 'launchy'
require 'socket'
require 'oauth2'
require 'oauth2/access_token'
require 'terminal-table'


QuizletNerdClient::Command.new.run
